name: GitHub CI Task

on:
    push:
        branches:
            - stable
            - ci-test

jobs:
    build_and_publish:
        name: Build and publish
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['24.x']
        steps:
        -
            uses: actions/checkout@v5
            with:
                ref: ${{ github.head_ref || github.ref_name }}
        -
            name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v7
            with:
                node-version: ${{ matrix.node-version }}
        -
            name: Install reference packages
            run: |
                npm install
                cd client
                npm install -g @angular/cli
                npm install
                cd ..
        -
            name: Pull Asphyxia CORE typedef file
            run: curl -o asphyxia.d.ts https://raw.githubusercontent.com/asphyxia-core/core/refs/heads/master/plugins/asphyxia-core.d.ts
        -
            name: Build
            id: build
            run: npm run build ghci
        -
            name: Create release
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                echo "**Please remove old version of this plugin and backup your Asphyxia CORE database files before install this update.**" > release-notes.md
                echo "" >> release-notes.md
                echo "**Since v2 update includes many breaking changes, we strongly recommend you to create a backup of Asphyxia CORE save file or you cannot scroll back to old version with your save data.**" >> release-notes.md
                echo "" >> release-notes.md
                echo "To install, unzip the \"rb\" folder into the directory of Asphyxia CORE plugins." >> release-notes.md
                echo "" >> release-notes.md
                echo "Incompatible with CORE versions below v1.50a." >> release-notes.md
                echo "" >> release-notes.md
                echo "*This file is auto generated by GitHub Actions.*" >> release-notes.md
                gh release create v${{ steps.build.outputs.version }} ./dist/${{ steps.build.outputs.dist_file_name }} --title $"v${{ steps.build.outputs.version }}" --notes-file release-notes.md